/**
 * Public entry point of the package.
 *
 * The CLI is the primary interface; these exports let the same logic be reused
 * programmatically without spawning a process.
 */
export {
  parseCliArgs,
  COMMANDS,
  DEFAULT_TARGET,
  type CliArgs,
  type CliCommand,
  type CliMode,
} from './cli/args.js';
export { formatHelp, formatVersion } from './cli/help.js';
export { createDefaultContext, runCli, type CliContext } from './cli/run.js';
export {
  analyzeCodebase,
  analyzeSource,
  buildGraph,
  collectExports,
  collectImports,
  collectRoutes,
  collectSymbols,
  collectTests,
  DEPENDENCY_KINDS,
  DEPENDENCY_ORIGINS,
  HTTP_METHODS,
  IMPORT_KINDS,
  isSourcePath,
  isTestPath,
  LANGUAGES,
  languageOf,
  parseSource,
  resolveSpecifier,
  ROUTE_SOURCES,
  scanSources,
  SOURCE_EXTENSIONS,
  summariseAnalysis,
  summariseSymbols,
  SYMBOL_KINDS,
  TEST_KINDS,
  type AnalysisSummary,
  type AnalyzeOptions,
  type ApiRoute,
  type CodebaseAnalysis,
  type CodeSymbol,
  type DependencyGraph,
  type DependencyKind,
  type DependencyOrigin,
  type FileAnalysis,
  type FileDependency,
  type HttpMethod,
  type ImportBinding,
  type ImportKind,
  type Language,
  type ModuleExport,
  type ModuleImport,
  type RouteSource,
  type ScannedFile,
  type ScanResult,
  type SkippedFile,
  type SourceLocation,
  type SymbolCounts,
  type SymbolDependency,
  type SymbolKind,
  type SymbolSummary,
  type TestCase,
  type TestKind,
} from './core/analysis/index.js';
export {
  CHANGE_KINDS,
  CHANGE_SCOPES,
  collectChanges,
  createGitRunner,
  findRepository,
  GitCommandError,
  GitUnavailableError,
  isGitUnavailableError,
  parseDiff,
  parseHunks,
  parseNumstat,
  parseStatus,
  readDiff,
  readHead,
  readStatus,
  requireChanges,
  splitPatch,
  summarise,
  type ChangeKind,
  type ChangeScope,
  type ChangeSet,
  type ChangeSummary,
  type CollectChangesOptions,
  type DiffFile,
  type DiffHunk,
  type DiffStats,
  type FileChange,
  type GitHead,
  type GitRepository,
  type GitResult,
  type GitRunner,
  type StatusEntry,
} from './core/git/index.js';
export {
  analyzeImpact,
  buildIncoming,
  DEFAULT_IMPACT_DEPTH,
  describeChange,
  IMPACT_RELATIONS,
  rebasePath,
  symbolsCovering,
  SYMBOL_PRECISIONS,
  touchedLines,
  traverseImpact,
  type AffectedComponent,
  type AffectedFile,
  type AffectedRoute,
  type AffectedTest,
  type ChangedFile,
  type ChangedSymbol,
  type ImpactAnalysis,
  type ImpactOptions,
  type ImpactReason,
  type ImpactRelation,
  type ImpactSummary,
  type SymbolPrecision,
} from './core/impact/index.js';
export { readManifest, type Manifest } from './core/manifest.js';
export {
  inspectProject,
  PACKAGE_MANAGERS,
  type PackageManager,
  type ProjectInfo,
} from './core/project.js';
export {
  createAnalysisReport,
  createChangesReport,
  createImpactReport,
  createReport,
  type AnalysisReport,
  type ChangesReport,
  type ImpactReport,
  type Report,
  type ToolInfo,
} from './core/report.js';
export { resolveTarget, resolveTargetPath, type Target } from './core/target.js';
export {
  formatAnalysisReport,
  formatChangesReport,
  formatImpactReport,
  formatReport,
  REPORT_FORMATS,
  type FormatOptions,
  type ReportFormat,
} from './reporters/index.js';
export { createPalette, shouldUseColor, type Palette } from './utils/color.js';
export { ExitCode, UsageError, VerifyError } from './utils/errors.js';
export { createLogger, type Logger } from './utils/logger.js';
export { TOOL_NAME, VERSION } from './version.js';
